In [1]:
import pandas as pd
import plotly.express as px

In [2]:
df_maths = pd.read_csv(r"..\data\student-mat.csv", delimiter=";")
df_por = pd.read_csv(r"..\data\student-por.csv", delimiter=";")

In [3]:
df_maths

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,5,5,4,4,5,4,11,9,9,9
391,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,3,14,16,16
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,5,3,3,3,3,3,10,8,7
393,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,0,11,12,10
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,2,3,3,3,5,5,8,9,9

In [19]:
df_maths.columns

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'G1', 'G2', 'G3'],
      dtype='str')

In [4]:
df_por

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,4,0,11,11
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,2,9,11,11
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,6,12,13,12
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,0,14,14,14
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,0,11,13,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
644,MS,F,19,R,GT3,T,2,3,services,other,...,5,4,2,1,2,5,4,10,11,10
645,MS,F,18,U,LE3,T,3,1,teacher,services,...,4,3,4,1,1,1,4,15,15,16
646,MS,F,18,U,GT3,T,1,1,other,other,...,1,1,1,1,1,5,6,11,12,9
647,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,6,10,10,10
648,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,4,10,11,11

In [5]:
df_maths.isna().sum().sum()
# no null value in maths dataframe

np.int64(0)

In [6]:
df_por.isna().sum().sum()
# no null value in por dataframe

np.int64(0)

In [7]:
df_maths.describe()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
count,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000
mean,16.696203,2.749367,2.521519,1.448101,2.035443,0.334177,3.944304,3.235443,3.108861,1.481013,2.291139,3.554430,5.708861,10.908861,10.713924,10.415190
std,1.276043,1.094735,1.088201,0.697505,0.839240,0.743651,0.896659,0.998862,1.113278,0.890741,1.287897,1.390303,8.003096,3.319195,3.761505,4.581443
min,15.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,3.000000,0.000000,0.000000
25%,16.000000,2.000000,2.000000,1.000000,1.000000,0.000000,4.000000,3.000000,2.000000,1.000000,1.000000,3.000000,0.000000,8.000000,9.000000,8.000000
50%,17.000000,3.000000,2.000000,1.000000,2.000000,0.000000,4.000000,3.000000,3.000000,1.000000,2.000000,4.000000,4.000000,11.000000,11.000000,11.000000
75%,18.000000,4.000000,3.000000,2.000000,2.000000,0.000000,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,8.000000,13.000000,13.000000,14.000000
max,22.000000,4.000000,4.000000,4.000000,4.000000,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,75.000000,19.000000,19.000000,20.000000

In [8]:
df_por.describe()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
count,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000
mean,16.744222,2.514638,2.306626,1.568567,1.930663,0.221880,3.930663,3.180277,3.184900,1.502311,2.280431,3.536210,3.659476,11.399076,11.570108,11.906009
std,1.218138,1.134552,1.099931,0.748660,0.829510,0.593235,0.955717,1.051093,1.175766,0.924834,1.284380,1.446259,4.640759,2.745265,2.913639,3.230656
min,15.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,16.000000,2.000000,1.000000,1.000000,1.000000,0.000000,4.000000,3.000000,2.000000,1.000000,1.000000,2.000000,0.000000,10.000000,10.000000,10.000000
50%,17.000000,2.000000,2.000000,1.000000,2.000000,0.000000,4.000000,3.000000,3.000000,1.000000,2.000000,4.000000,2.000000,11.000000,11.000000,12.000000
75%,18.000000,4.000000,3.000000,2.000000,2.000000,0.000000,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,6.000000,13.000000,13.000000,14.000000
max,22.000000,4.000000,4.000000,4.000000,4.000000,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,32.000000,19.000000,19.000000,19.000000

In [9]:
# so we hyave to make aregresion model, y = G3 (final grade)
# it would be better if we make 3 model
# one for predicting G3, before first period exam--> mean we will not be using G1(first period grade) and G2(second period grade)
# one for predicting G3, before second period exam--> mean we will not be using G2(second period grade)
# one for predicting G3, before final exam--> mean we will  be using both G1 and G2 to do better prediction

In [10]:
df_maths.info()

<class 'pandas.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      395 non-null    str
 1   sex         395 non-null    str
 2   age         395 non-null    int64
 3   address     395 non-null    str
 4   famsize     395 non-null    str
 5   Pstatus     395 non-null    str
 6   Medu        395 non-null    int64
 7   Fedu        395 non-null    int64
 8   Mjob        395 non-null    str
 9   Fjob        395 non-null    str
 10  reason      395 non-null    str
 11  guardian    395 non-null    str
 12  traveltime  395 non-null    int64
 13  studytime   395 non-null    int64
 14  failures    395 non-null    int64
 15  schoolsup   395 non-null    str
 16  famsup      395 non-null    str
 17  paid        395 non-null    str
 18  activities  395 non-null    str
 19  nursery     395 non-null    str
 20  higher      395 non-null    str
 21  internet    395 non-null    str
 22  romantic    395 non-null    str
 23  famrel      395 non-null    int64
 24  freetime    395 non-null    int64
 25  goout       395 non-null    int64
 26  Dalc        395 non-null    int64
 27  Walc        395 non-null    int64
 28  health      395 non-null    int64
 29  absences    395 non-null    int64
 30  G1          395 non-null    int64
 31  G2          395 non-null    int64
 32  G3          395 non-null    int64
dtypes: int64(16), str(17)
memory usage: 102.0 KB

In [20]:
# Columns used to identify the same student
id_cols = [
    "school", "sex", "age", "address", "famsize", "Pstatus", 
    "Medu", "Fedu", "Mjob", "Fjob", "reason", "nursery", "internet"
]

# Merge to find common students
common_students = pd.merge(df_maths, df_por, on=id_cols, how='inner')

print(f"Total in Math: {len(df_maths)}")
print(f"Total in Portuguese: {len(df_por)}")
print(f"Students present in both: {len(common_students)}")

Total in Math: 395
Total in Portuguese: 649
Students present in both: 382

In [23]:
common_students[['G3_x','G3_y']].corr()

          G3_x      G3_y
G3_x  1.000000  0.480349
G3_y  0.480349  1.000000

In [ ]:
# not a very high correlation
# so training seperate model to predict maths marks and portugies marks would be better

## numarical feature

In [11]:
df_maths.select_dtypes(include='number').corr().iloc[-3:,:].round(2)

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
G1,-0.06,0.21,0.19,-0.09,0.16,-0.35,0.02,0.01,-0.15,-0.09,-0.13,-0.07,-0.03,1.00,0.85,0.8
G2,-0.14,0.22,0.16,-0.15,0.14,-0.36,-0.02,-0.01,-0.16,-0.06,-0.08,-0.10,-0.03,0.85,1.00,0.9
G3,-0.16,0.22,0.15,-0.12,0.10,-0.36,0.05,0.01,-0.13,-0.05,-0.05,-0.06,0.03,0.80,0.90,1.0

In [17]:
fig = px.imshow(df_maths.select_dtypes(include='number').corr().iloc[-3:,:].round(2),
                text_auto=True,color_continuous_midpoint=0)
fig.show()

In [18]:
fig = px.imshow(df_por.select_dtypes(include='number').corr().iloc[-3:,:].round(2),
                text_auto=True,color_continuous_midpoint=0)
fig.show()

In [ ]:
# G3 have high correlation with with G!, G2, failure
# G3 have low correlation with quality of family relation,freetime, going out, health, absence

## categorical features

In [31]:
df_maths.select_dtypes(include=['str']).nunique()

school        2
sex           2
address       2
famsize       2
Pstatus       2
Mjob          5
Fjob          5
reason        4
guardian      3
schoolsup     2
famsup        2
paid          2
activities    2
nursery       2
higher        2
internet      2
romantic      2
dtype: int64

In [46]:
df_maths['schoolsup'].unique()

<StringArray>
['yes', 'no']
Length: 2, dtype: str

In [32]:
df_por.select_dtypes(include=['str']).nunique()

school        2
sex           2
address       2
famsize       2
Pstatus       2
Mjob          5
Fjob          5
reason        4
guardian      3
schoolsup     2
famsup        2
paid          2
activities    2
nursery       2
higher        2
internet      2
romantic      2
dtype: int64

### using Mutual Information (MI)

In [39]:
from sklearn.feature_selection import mutual_info_regression
from sklearn.preprocessing import LabelEncoder

In [40]:
# Label encoding categorical columns
df_cat = df_maths.select_dtypes(include=['str']).copy()
for col in df_cat.columns:
    df_cat[col] = LabelEncoder().fit_transform(df_cat[col])

In [41]:
# Calculate MI
mi_scores = mutual_info_regression(df_cat, df_maths['G3'], discrete_features=True)

mi_results = pd.Series(mi_scores, index=df_cat.columns).sort_values(ascending=False)
print(mi_results)

paid          0.055240
schoolsup     0.037158
sex           0.035022
Mjob          0.020485
romantic      0.020408
higher        0.015168
reason        0.007104
famsize       0.004314
address       0.003442
guardian      0.003056
school        0.000000
Fjob          0.000000
Pstatus       0.000000
activities    0.000000
famsup        0.000000
nursery       0.000000
internet      0.000000
dtype: float64

In [42]:
df_cat = df_por.select_dtypes(include=['str']).copy()
for col in df_cat.columns:
    df_cat[col] = LabelEncoder().fit_transform(df_cat[col])

mi_scores = mutual_info_regression(df_cat, df_por['G3'], discrete_features=True)
mi_results = pd.Series(mi_scores, index=df_cat.columns).sort_values(ascending=False)
mi_results

higher        0.076382
reason        0.058646
Mjob          0.055631
address       0.051699
school        0.035326
Fjob          0.026788
famsize       0.020123
internet      0.015870
schoolsup     0.013298
sex           0.007156
famsup        0.005506
paid          0.003848
romantic      0.002764
guardian      0.000000
Pstatus       0.000000
activities    0.000000
nursery       0.000000
dtype: float64