In [2]:
import pandas as pd
import numpy as np
import plotly.express as px
import xgboost as xgb
from sklearn.model_selection import GroupKFold
from sklearn.metrics import mean_absolute_error, r2_score, mean_squared_error
import optuna
import joblib

In [3]:
df_maths = pd.read_csv(r"..\data\student-mat.csv", delimiter=";")
df_por = pd.read_csv(r"..\data\student-por.csv", delimiter=";")

df_maths['subject'] = 'Maths'
df_por['subject']= 'Portuguese'

df = pd.concat([df_maths, df_por], axis=0).reset_index(drop=True)

id_cols = ["school", "sex", "age", "address", "famsize", "Pstatus", 
           "Medu", "Fedu", "Mjob", "Fjob", "reason", "nursery", "internet"]

df['student_id'] = df[id_cols].astype(str).agg('-'.join, axis=1)

#  target
target = 'G3'

# feature sets
demographic_features = [col for col in df.columns if col not in ['G1', 'G2', 'G3', 'student_id']]

# Categorical columns 
cat_features = df[demographic_features].select_dtypes(include=['str']).columns.tolist()
for col in cat_features:
    df[col] = df[col].astype('category') 

# feature sets for  3 models
features_model1 = demographic_features
features_model2 = demographic_features + ['G1']
features_model3 = demographic_features + ['G1', 'G2']

## Model 2 (After G1)

In [4]:
X = df[features_model2]
y = df['G3']
groups = df['student_id']

def objective(trial):

    params = {"tree_method": "hist","objective": "reg:squarederror","random_state": 42,
              "enable_categorical" :True, "n_estimators":1000,  #"early_stopping_rounds":50,
              
              "n_estimators": trial.suggest_int("n_estimators",200,1000),
              "max_depth": trial.suggest_int("max_depth",3,10),
              "learning_rate": trial.suggest_float("learning_rate",0.005,0.1,log=True),
              "subsample": trial.suggest_float("subsample",0.5,1.0),
              "colsample_bytree": trial.suggest_float("colsample_bytree",0.5,1.0),
              "min_child_weight": trial.suggest_int("min_child_weight",1,15),
              "gamma": trial.suggest_float("gamma",0,5),
              #"reg_alpha": trial.suggest_float("reg_alpha",1e-4,10,log=True),
              "reg_lambda": trial.suggest_float("reg_lambda",1e-4,10,log=True),
    }
    
    gkf = GroupKFold(n_splits=5)
    mae_scores = []

    for train_idx, val_idx in gkf.split(X, y, groups=groups):

        X_train, X_val = X.iloc[train_idx], X.iloc[val_idx]
        y_train, y_val = y.iloc[train_idx], y.iloc[val_idx]
        
        model = xgb.XGBRegressor(**params)
        
        model.fit(
            X_train, y_train,
            eval_set=[(X_val, y_val)],
            verbose=False
        )
        
        preds = model.predict(X_val)
        mae_scores.append(mean_absolute_error(y_val, preds))

    return np.mean(mae_scores)

In [5]:
study = optuna.create_study(
    direction="minimize"
)

study.optimize(
    objective,
    n_trials=200,
    show_progress_bar=True
)

[I 2026-05-13 04:05:21,609] A new study created in memory with name: no-name-fe1c3d08-3ba0-4178-ab3c-818874e9d82c

  0%|          | 0/200 [00:00<?, ?it/s]

[I 2026-05-13 04:05:23,780] Trial 0 finished with value: 1.3540875911712646 and parameters: {'n_estimators': 662, 'max_depth': 10, 'learning_rate': 0.03302731336021678, 'subsample': 0.5465369385301492, 'colsample_bytree': 0.9906332163787257, 'min_child_weight': 9, 'gamma': 2.8868211091090643, 'reg_lambda': 0.0032612065058309227}. Best is trial 0 with value: 1.3540875911712646.
[I 2026-05-13 04:05:26,567] Trial 1 finished with value: 1.4301870346069336 and parameters: {'n_estimators': 699, 'max_depth': 8, 'learning_rate': 0.05919434844053432, 'subsample': 0.7259078522210154, 'colsample_bytree': 0.9885616768539893, 'min_child_weight': 13, 'gamma': 0.0896759254817392, 'reg_lambda': 0.003899948770721614}. Best is trial 0 with value: 1.3540875911712646.
[I 2026-05-13 04:05:27,931] Trial 2 finished with value: 1.4349199056625366 and parameters: {'n_estimators': 628, 'max_depth': 6, 'learning_rate': 0.0913674979267306, 'subsample': 0.965440899011079, 'colsample_bytree': 0.5456997965773114, 'min_child_weight': 3, 'gamma': 0.49117873290272895, 'reg_lambda': 0.30448183485450575}. Best is trial 0 with value: 1.3540875911712646.
[I 2026-05-13 04:05:30,601] Trial 3 finished with value: 1.3378789663314818 and parameters: {'n_estimators': 939, 'max_depth': 4, 'learning_rate': 0.005379383767418159, 'subsample': 0.951256193093193, 'colsample_bytree': 0.8813337149978686, 'min_child_weight': 10, 'gamma': 1.351750139958357, 'reg_lambda': 2.270149719687413}. Best is trial 3 with value: 1.3378789663314818.
[I 2026-05-13 04:05:32,376] Trial 4 finished with value: 1.3631261110305786 and parameters: {'n_estimators': 371, 'max_depth': 10, 'learning_rate': 0.02374808440552343, 'subsample': 0.7064676316824605, 'colsample_bytree': 0.9395336331130555, 'min_child_weight': 11, 'gamma': 0.8015236357631472, 'reg_lambda': 0.8815611204916898}. Best is trial 3 with value: 1.3378789663314818.
[I 2026-05-13 04:05:34,650] Trial 5 finished with value: 1.4235137224197387 and parameters: {'n_estimators': 604, 'max_depth': 7, 'learning_rate': 0.035258317924976204, 'subsample': 0.5535131027573414, 'colsample_bytree': 0.9672859852190141, 'min_child_weight': 12, 'gamma': 0.4099180381666184, 'reg_lambda': 0.007609983716805697}. Best is trial 3 with value: 1.3378789663314818.
[I 2026-05-13 04:05:37,674] Trial 6 finished with value: 1.3688478469848633 and parameters: {'n_estimators': 975, 'max_depth': 4, 'learning_rate': 0.006649070627238706, 'subsample': 0.5819161852190748, 'colsample_bytree': 0.5163221863706317, 'min_child_weight': 15, 'gamma': 1.434373667581243, 'reg_lambda': 0.0006848016821887633}. Best is trial 3 with value: 1.3378789663314818.
[I 2026-05-13 04:05:39,268] Trial 7 finished with value: 1.427015495300293 and parameters: {'n_estimators': 565, 'max_depth': 4, 'learning_rate': 0.054876432609335994, 'subsample': 0.5653961112392956, 'colsample_bytree': 0.703867404350103, 'min_child_weight': 15, 'gamma': 2.3767430864140997, 'reg_lambda': 0.090240398181649}. Best is trial 3 with value: 1.3378789663314818.
[I 2026-05-13 04:05:40,512] Trial 8 finished with value: 1.3867405652999878 and parameters: {'n_estimators': 348, 'max_depth': 9, 'learning_rate': 0.019792068540474307, 'subsample': 0.8797116093706758, 'colsample_bytree': 0.5366336609290283, 'min_child_weight': 9, 'gamma': 4.702762066085147, 'reg_lambda': 0.21748017297354938}. Best is trial 3 with value: 1.3378789663314818.
[I 2026-05-13 04:05:41,354] Trial 9 finished with value: 1.371626043319702 and parameters: {'n_estimators': 318, 'max_depth': 10, 'learning_rate': 0.09121011268042399, 'subsample': 0.6727006239197998, 'colsample_bytree': 0.9985123950710988, 'min_child_weight': 4, 'gamma': 3.942425435790848, 'reg_lambda': 0.08981070535816675}. Best is trial 3 with value: 1.3378789663314818.
[I 2026-05-13 04:05:43,773] Trial 10 finished with value: 1.3595725536346435 and parameters: {'n_estimators': 970, 'max_depth': 3, 'learning_rate': 0.00504007339663086, 'subsample': 0.847460191830731, 'colsample_bytree': 0.8337641308350374, 'min_child_weight': 6, 'gamma': 1.7823780971749725, 'reg_lambda': 8.951474547293802}. Best is trial 3 with value: 1.3378789663314818.
[I 2026-05-13 04:05:46,071] Trial 11 finished with value: 1.3503933429718018 and parameters: {'n_estimators': 813, 'max_depth': 5, 'learning_rate': 0.010641566830432502, 'subsample': 0.9806059158969059, 'colsample_bytree': 0.8628527168982434, 'min_child_weight': 8, 'gamma': 2.9120124950627173, 'reg_lambda': 0.00025330214542468185}. Best is trial 3 with value: 1.3378789663314818.
[I 2026-05-13 04:05:48,757] Trial 12 finished with value: 1.3522691488265992 and parameters: {'n_estimators': 825, 'max_depth': 5, 'learning_rate': 0.00990459970000989, 'subsample': 0.96185270754666, 'colsample_bytree': 0.8401945120201404, 'min_child_weight': 7, 'gamma': 2.8318559766256346, 'reg_lambda': 0.00011189652938987764}. Best is trial 3 with value: 1.3378789663314818.
[I 2026-05-13 04:05:51,116] Trial 13 finished with value: 1.3398235321044922 and parameters: {'n_estimators': 809, 'max_depth': 5, 'learning_rate': 0.010950653803539842, 'subsample': 0.8318835003370922, 'colsample_bytree': 0.8422009768479573, 'min_child_weight': 1, 'gamma': 3.4041990151500574, 'reg_lambda': 9.065264766631707}. Best is trial 3 with value: 1.3378789663314818.
[I 2026-05-13 04:05:53,412] Trial 14 finished with value: 1.3578201055526733 and parameters: {'n_estimators': 846, 'max_depth': 3, 'learning_rate': 0.01156223547159053, 'subsample': 0.8276637620531035, 'colsample_bytree': 0.7414808103577529, 'min_child_weight': 1, 'gamma': 3.720882623442858, 'reg_lambda': 8.758502309279502}. Best is trial 3 with value: 1.3378789663314818.
[I 2026-05-13 04:05:56,789] Trial 15 finished with value: 1.367056941986084 and parameters: {'n_estimators': 901, 'max_depth': 6, 'learning_rate': 0.007109058735060685, 'subsample': 0.8919250305492599, 'colsample_bytree': 0.6619566336064614, 'min_child_weight': 5, 'gamma': 1.5133910811050981, 'reg_lambda': 1.323363410464826}. Best is trial 3 with value: 1.3378789663314818.
[I 2026-05-13 04:05:58,266] Trial 16 finished with value: 1.3454442501068116 and parameters: {'n_estimators': 475, 'max_depth': 5, 'learning_rate': 0.016258972524436654, 'subsample': 0.7819463863266493, 'colsample_bytree': 0.8938031970193598, 'min_child_weight': 1, 'gamma': 3.6600565013859163, 'reg_lambda': 2.377207645425798}. Best is trial 3 with value: 1.3378789663314818.
[I 2026-05-13 04:06:00,537] Trial 17 finished with value: 1.3454205513000488 and parameters: {'n_estimators': 742, 'max_depth': 4, 'learning_rate': 0.005028895110988471, 'subsample': 0.9085193540288319, 'colsample_bytree': 0.789082670270673, 'min_child_weight': 10, 'gamma': 2.056703493695043, 'reg_lambda': 2.548250718884069}. Best is trial 3 with value: 1.3378789663314818.
[I 2026-05-13 04:06:03,628] Trial 18 finished with value: 1.363609743118286 and parameters: {'n_estimators': 760, 'max_depth': 7, 'learning_rate': 0.008332028681108185, 'subsample': 0.7984143952227123, 'colsample_bytree': 0.8968150961931716, 'min_child_weight': 3, 'gamma': 1.1238720888812654, 'reg_lambda': 0.015157411816229788}. Best is trial 3 with value: 1.3378789663314818.
[I 2026-05-13 04:06:05,774] Trial 19 finished with value: 1.3627127170562745 and parameters: {'n_estimators': 909, 'max_depth': 3, 'learning_rate': 0.01497014013208885, 'subsample': 0.9277429924532191, 'colsample_bytree': 0.6386255800978646, 'min_child_weight': 7, 'gamma': 4.778516651641596, 'reg_lambda': 9.589121756236198}. Best is trial 3 with value: 1.3378789663314818.
[I 2026-05-13 04:06:07,498] Trial 20 finished with value: 1.341204571723938 and parameters: {'n_estimators': 482, 'max_depth': 6, 'learning_rate': 0.013401393074348207, 'subsample': 0.6651083464064821, 'colsample_bytree': 0.7856204206317325, 'min_child_weight': 12, 'gamma': 3.35235160241119, 'reg_lambda': 0.5763156823885881}. Best is trial 3 with value: 1.3378789663314818.
[I 2026-05-13 04:06:08,383] Trial 21 finished with value: 1.3679770946502685 and parameters: {'n_estimators': 207, 'max_depth': 6, 'learning_rate': 0.01413584458836527, 'subsample': 0.6251684059439622, 'colsample_bytree': 0.7912592121111696, 'min_child_weight': 13, 'gamma': 3.2469682095060275, 'reg_lambda': 0.6093522316964902}. Best is trial 3 with value: 1.3378789663314818.
[I 2026-05-13 04:06:10,313] Trial 22 finished with value: 1.3494071960449219 and parameters: {'n_estimators': 557, 'max_depth': 5, 'learning_rate': 0.0075666635484212845, 'subsample': 0.6289673880278668, 'colsample_bytree': 0.779024906832232, 'min_child_weight': 11, 'gamma': 4.151095969908554, 'reg_lambda': 3.295846773386554}. Best is trial 3 with value: 1.3378789663314818.
[I 2026-05-13 04:06:11,943] Trial 23 finished with value: 1.3510011672973632 and parameters: {'n_estimators': 517, 'max_depth': 4, 'learning_rate': 0.021292662582898532, 'subsample': 0.7812912937929211, 'colsample_bytree': 0.9112998538977773, 'min_child_weight': 13, 'gamma': 3.3956512322611707, 'reg_lambda': 0.4447616843267298}. Best is trial 3 with value: 1.3378789663314818.
[I 2026-05-13 04:06:13,797] Trial 24 finished with value: 1.338631796836853 and parameters: {'n_estimators': 454, 'max_depth': 7, 'learning_rate': 0.012421794077164492, 'subsample': 0.6838638015370283, 'colsample_bytree': 0.8357693943522352, 'min_child_weight': 10, 'gamma': 2.44247677868924, 'reg_lambda': 0.12081712304668737}. Best is trial 3 with value: 1.3378789663314818.
[I 2026-05-13 04:06:16,976] Trial 25 finished with value: 1.3455310344696045 and parameters: {'n_estimators': 909, 'max_depth': 7, 'learning_rate': 0.008983941491791436, 'subsample': 0.8453230265473636, 'colsample_bytree': 0.8533727526056859, 'min_child_weight': 9, 'gamma': 2.3102468355194508, 'reg_lambda': 0.15745879591921402}. Best is trial 3 with value: 1.3378789663314818.
[I 2026-05-13 04:06:18,987] Trial 26 finished with value: 1.3643962383270263 and parameters: {'n_estimators': 424, 'max_depth': 8, 'learning_rate': 0.005830552387951166, 'subsample': 0.744093208277494, 'colsample_bytree': 0.9315652749757586, 'min_child_weight': 10, 'gamma': 1.9688807766918521, 'reg_lambda': 0.027148601995443382}. Best is trial 3 with value: 1.3378789663314818.
[I 2026-05-13 04:06:19,975] Trial 27 finished with value: 1.3586974382400512 and parameters: {'n_estimators': 254, 'max_depth': 8, 'learning_rate': 0.027057653686295178, 'subsample': 0.9339802041859645, 'colsample_bytree': 0.7268219843326312, 'min_child_weight': 7, 'gamma': 4.268246708048345, 'reg_lambda': 3.6826299051642843}. Best is trial 3 with value: 1.3378789663314818.
[I 2026-05-13 04:06:22,833] Trial 28 finished with value: 1.3770036458969117 and parameters: {'n_estimators': 993, 'max_depth': 5, 'learning_rate': 0.017567668972656006, 'subsample': 0.5145681150139787, 'colsample_bytree': 0.8169929770389456, 'min_child_weight': 10, 'gamma': 2.6836689737322543, 'reg_lambda': 0.07149054241238975}. Best is trial 3 with value: 1.3378789663314818.
[I 2026-05-13 04:06:24,684] Trial 29 finished with value: 1.3484389543533326 and parameters: {'n_estimators': 651, 'max_depth': 4, 'learning_rate': 0.01166137208205864, 'subsample': 0.9964618291123902, 'colsample_bytree': 0.887402394798311, 'min_child_weight': 8, 'gamma': 1.1532994527663603, 'reg_lambda': 1.8782937996026299}. Best is trial 3 with value: 1.3378789663314818.
[I 2026-05-13 04:06:27,816] Trial 30 finished with value: 1.3493579387664796 and parameters: {'n_estimators': 695, 'max_depth': 9, 'learning_rate': 0.006183207339196926, 'subsample': 0.6921780477248864, 'colsample_bytree': 0.9481912002853305, 'min_child_weight': 5, 'gamma': 3.048193559182123, 'reg_lambda': 0.0012913078815291151}. Best is trial 3 with value: 1.3378789663314818.
[I 2026-05-13 04:06:29,685] Trial 31 finished with value: 1.3387880802154541 and parameters: {'n_estimators': 455, 'max_depth': 6, 'learning_rate': 0.012877056687340212, 'subsample': 0.6563904260348065, 'colsample_bytree': 0.8161182219930574, 'min_child_weight': 12, 'gamma': 3.3865910466675584, 'reg_lambda': 0.647790241933909}. Best is trial 3 with value: 1.3378789663314818.
[I 2026-05-13 04:06:31,318] Trial 32 finished with value: 1.3586402177810668 and parameters: {'n_estimators': 396, 'max_depth': 7, 'learning_rate': 0.03028133317362384, 'subsample': 0.6421996598436235, 'colsample_bytree': 0.8678701284502363, 'min_child_weight': 11, 'gamma': 2.6168145275847245, 'reg_lambda': 4.766388763542164}. Best is trial 3 with value: 1.3378789663314818.
[I 2026-05-13 04:06:33,095] Trial 33 finished with value: 1.344408130645752 and parameters: {'n_estimators': 477, 'max_depth': 6, 'learning_rate': 0.012430671952867331, 'subsample': 0.7306597331219635, 'colsample_bytree': 0.8150363444382517, 'min_child_weight': 14, 'gamma': 4.381436867970952, 'reg_lambda': 1.085833481541735}. Best is trial 3 with value: 1.3378789663314818.
[I 2026-05-13 04:06:34,722] Trial 34 finished with value: 1.3423381328582764 and parameters: {'n_estimators': 437, 'max_depth': 6, 'learning_rate': 0.008935456623310077, 'subsample': 0.5964334239022183, 'colsample_bytree': 0.7588519058870299, 'min_child_weight': 9, 'gamma': 3.6244511212044426, 'reg_lambda': 0.3047085549281378}. Best is trial 3 with value: 1.3378789663314818.
[I 2026-05-13 04:06:36,592] Trial 35 finished with value: 1.3577540636062622 and parameters: {'n_estimators': 561, 'max_depth': 5, 'learning_rate': 0.01823282689730134, 'subsample': 0.7072987910442938, 'colsample_bytree': 0.8177442096125079, 'min_child_weight': 12, 'gamma': 0.24271939093167294, 'reg_lambda': 0.03682654427871723}. Best is trial 3 with value: 1.3378789663314818.
[I 2026-05-13 04:06:37,764] Trial 36 finished with value: 1.360015058517456 and parameters: {'n_estimators': 309, 'max_depth': 7, 'learning_rate': 0.009832946122162789, 'subsample': 0.603670200373791, 'colsample_bytree': 0.8727506298221903, 'min_child_weight': 14, 'gamma': 0.6682817185182477, 'reg_lambda': 1.446328807256548}. Best is trial 3 with value: 1.3378789663314818.
[I 2026-05-13 04:06:40,524] Trial 37 finished with value: 1.3423682928085328 and parameters: {'n_estimators': 769, 'max_depth': 8, 'learning_rate': 0.007840665000216003, 'subsample': 0.777539823567208, 'colsample_bytree': 0.91991399450976, 'min_child_weight': 11, 'gamma': 3.1356460372999355, 'reg_lambda': 0.7637102932402952}. Best is trial 3 with value: 1.3378789663314818.
[I 2026-05-13 04:06:42,499] Trial 38 finished with value: 1.3777440547943116 and parameters: {'n_estimators': 619, 'max_depth': 9, 'learning_rate': 0.023029107749232378, 'subsample': 0.662366375874958, 'colsample_bytree': 0.681139903785706, 'min_child_weight': 10, 'gamma': 2.2687855064254308, 'reg_lambda': 5.326244460761999}. Best is trial 3 with value: 1.3378789663314818.
[I 2026-05-13 04:06:44,703] Trial 39 finished with value: 1.3536806106567383 and parameters: {'n_estimators': 858, 'max_depth': 6, 'learning_rate': 0.0156782602862537, 'subsample': 0.6996919026226854, 'colsample_bytree': 0.9725240074470571, 'min_child_weight': 2, 'gamma': 1.7263544481726343, 'reg_lambda': 0.15350656260524262}. Best is trial 3 with value: 1.3378789663314818.
[I 2026-05-13 04:06:46,503] Trial 40 finished with value: 1.4041774988174438 and parameters: {'n_estimators': 702, 'max_depth': 4, 'learning_rate': 0.04227875932463275, 'subsample': 0.7587951094518233, 'colsample_bytree': 0.5938317975058454, 'min_child_weight': 12, 'gamma': 1.165856640875719, 'reg_lambda': 0.36684131386411395}. Best is trial 3 with value: 1.3378789663314818.
[I 2026-05-13 04:06:48,116] Trial 41 finished with value: 1.3495867729187012 and parameters: {'n_estimators': 504, 'max_depth': 6, 'learning_rate': 0.01319580879590786, 'subsample': 0.6792192193912162, 'colsample_bytree': 0.7613996814391469, 'min_child_weight': 12, 'gamma': 3.4624329844914095, 'reg_lambda': 0.6114616112171184}. Best is trial 3 with value: 1.3378789663314818.
[I 2026-05-13 04:06:49,633] Trial 42 finished with value: 1.3441209077835083 and parameters: {'n_estimators': 441, 'max_depth': 7, 'learning_rate': 0.012827403000727147, 'subsample': 0.6592139254965403, 'colsample_bytree': 0.8030074160765652, 'min_child_weight': 14, 'gamma': 3.9020918874059376, 'reg_lambda': 0.9966145278965219}. Best is trial 3 with value: 1.3378789663314818.
[I 2026-05-13 04:06:50,806] Trial 43 finished with value: 1.3401274681091309 and parameters: {'n_estimators': 369, 'max_depth': 5, 'learning_rate': 0.009872525848824974, 'subsample': 0.7253007717339612, 'colsample_bytree': 0.8424774936958723, 'min_child_weight': 12, 'gamma': 2.9257692977919816, 'reg_lambda': 0.2134695285969631}. Best is trial 3 with value: 1.3378789663314818.
[I 2026-05-13 04:06:51,970] Trial 44 finished with value: 1.3814590930938722 and parameters: {'n_estimators': 356, 'max_depth': 5, 'learning_rate': 0.0067801264033685495, 'subsample': 0.723928049957842, 'colsample_bytree': 0.8408605579625553, 'min_child_weight': 13, 'gamma': 2.9102188612265345, 'reg_lambda': 0.05465717343994366}. Best is trial 3 with value: 1.3378789663314818.
[I 2026-05-13 04:06:52,942] Trial 45 finished with value: 1.3463265895843506 and parameters: {'n_estimators': 282, 'max_depth': 5, 'learning_rate': 0.011165916020619898, 'subsample': 0.8639680115601965, 'colsample_bytree': 0.8332969834788804, 'min_child_weight': 11, 'gamma': 2.4261739521260326, 'reg_lambda': 0.16860324667910706}. Best is trial 3 with value: 1.3378789663314818.
[I 2026-05-13 04:06:54,079] Trial 46 finished with value: 1.3873467206954957 and parameters: {'n_estimators': 393, 'max_depth': 4, 'learning_rate': 0.005844021386577673, 'subsample': 0.8273585444617797, 'colsample_bytree': 0.8839650013275719, 'min_child_weight': 9, 'gamma': 2.7370232850655136, 'reg_lambda': 0.2573530971964508}. Best is trial 3 with value: 1.3378789663314818.
[I 2026-05-13 04:06:56,335] Trial 47 finished with value: 1.3404326438903809 and parameters: {'n_estimators': 970, 'max_depth': 3, 'learning_rate': 0.009694376257203624, 'subsample': 0.9503482105143994, 'colsample_bytree': 0.8548729272496328, 'min_child_weight': 10, 'gamma': 3.971016448724242, 'reg_lambda': 0.00732010894113155}. Best is trial 3 with value: 1.3378789663314818.
[I 2026-05-13 04:06:57,850] Trial 48 finished with value: 1.3336711883544923 and parameters: {'n_estimators': 584, 'max_depth': 5, 'learning_rate': 0.01892913242761783, 'subsample': 0.8066106319525581, 'colsample_bytree': 0.8260668446994297, 'min_child_weight': 8, 'gamma': 4.530796820607167, 'reg_lambda': 0.10902178440258871}. Best is trial 48 with value: 1.3336711883544923.
[I 2026-05-13 04:06:59,010] Trial 49 finished with value: 1.344999861717224 and parameters: {'n_estimators': 552, 'max_depth': 4, 'learning_rate': 0.025745456696125196, 'subsample': 0.8035394626293372, 'colsample_bytree': 0.7098894919541248, 'min_child_weight': 6, 'gamma': 4.959325318888735, 'reg_lambda': 0.10169069573636955}. Best is trial 48 with value: 1.3336711883544923.
[I 2026-05-13 04:07:00,511] Trial 50 finished with value: 1.3358827114105225 and parameters: {'n_estimators': 599, 'max_depth': 5, 'learning_rate': 0.019742586431480035, 'subsample': 0.9114396999867993, 'colsample_bytree': 0.9079103421683603, 'min_child_weight': 3, 'gamma': 4.6184837999366595, 'reg_lambda': 5.460768440662383}. Best is trial 48 with value: 1.3336711883544923.
[I 2026-05-13 04:07:01,837] Trial 51 finished with value: 1.3390887260437012 and parameters: {'n_estimators': 595, 'max_depth': 5, 'learning_rate': 0.019970569516440537, 'subsample': 0.9010129487814724, 'colsample_bytree': 0.9575760404695156, 'min_child_weight': 2, 'gamma': 4.44670366633754, 'reg_lambda': 6.713987483183391}. Best is trial 48 with value: 1.3336711883544923.

In [6]:
trial_df = study.trials_dataframe()
fig = px.line(
    trial_df,
    x="number",
    y="value",
    title="Optuna Optimization History",template = "presentation"
)
fig.show()

In [7]:
print("Best MAE:")
print(study.best_value)

print("\nBest Parameters:")
print(study.best_params)

Best MAE:
1.3183340311050415

Best Parameters:
{'n_estimators': 422, 'max_depth': 4, 'learning_rate': 0.044612033222283375, 'subsample': 0.9604275190847189, 'colsample_bytree': 0.9792930197363612, 'min_child_weight': 3, 'gamma': 4.385668613911848, 'reg_lambda': 3.569836871987955}

In [8]:
def evaluate(df, feature_list, best_params, target_col='G3'):
    X = df[feature_list]
    y = df[target_col]
    groups = df['student_id']
    
    gkf = GroupKFold(n_splits=5)
    
    mae_scores = []
    mse_scores = []
    r2_scores = []
    
    print(f"\n--- Training Model with {len(feature_list)} features ---")
    
    for train_idx, val_idx in gkf.split(X, y, groups=groups):
        X_train, X_val = X.iloc[train_idx], X.iloc[val_idx]
        y_train, y_val = y.iloc[train_idx], y.iloc[val_idx]
        
        model = xgb.XGBRegressor(**best_params, tree_method= "hist",objective= "reg:squarederror",random_state= 42,
              enable_categorical =True)
        
        model.fit(
            X_train, y_train,
            eval_set=[(X_val, y_val)],
            verbose=False
        )
        
        preds = model.predict(X_val)
        mae_scores.append(mean_absolute_error(y_val, preds))
        mse_scores.append(mean_squared_error(y_val, preds))
        r2_scores.append(r2_score(y_val, preds))
        
    print('MAE :',mae_scores)    
    print(f"Average MAE: {np.mean(mae_scores):.4f}")
    print('MSE :',mse_scores)    
    print(f"Average MSE: {np.mean(mse_scores):.4f}")
    print('r2_scores : ',r2_scores)
    print(f"Average R2: {np.mean(r2_scores):.4f}")

In [9]:
# Evaluating Model 2 (After G1)
evaluate(df, features_model2, best_params=study.best_params)

--- Training Model with 32 features ---
MAE : [1.273879051208496, 1.3527376651763916, 1.333192229270935, 1.3188145160675049, 1.3130466938018799]
Average MAE: 1.3183
MSE : [3.4704980850219727, 3.5349392890930176, 3.53712797164917, 4.1342387199401855, 4.051673889160156]
Average MSE: 3.7457
r2_scores :  [0.7466739416122437, 0.7169796228408813, 0.7639843225479126, 0.7430263757705688, 0.7635051608085632]
Average R2: 0.7468

In [10]:
# final model 2 (using the whole data)
model_2 = xgb.XGBRegressor(**study.best_params, tree_method= "hist",objective= "reg:squarederror",random_state= 42,
              enable_categorical =True)
model_2.fit(
            X, y,
            verbose=True
        )

pred = model_2.predict(X)
mean_absolute_error(pred,y)

1.0099622011184692

In [11]:
import json

# Save the model itself
model_2.save_model("model_2.json")

## Model 3 (Final prediction after G2)

In [12]:
X = df[features_model3]
y = df['G3']
groups = df['student_id']

def objective(trial):

    params = {"tree_method": "hist","objective": "reg:squarederror","random_state": 42,
              "enable_categorical" :True, "n_estimators":1000,  #"early_stopping_rounds":50,
              
              "n_estimators": trial.suggest_int("n_estimators",200,1000),
              "max_depth": trial.suggest_int("max_depth",3,10),
              "learning_rate": trial.suggest_float("learning_rate",0.005,0.1,log=True),
              "subsample": trial.suggest_float("subsample",0.5,1.0),
              "colsample_bytree": trial.suggest_float("colsample_bytree",0.5,1.0),
              "min_child_weight": trial.suggest_int("min_child_weight",1,15),
              "gamma": trial.suggest_float("gamma",0,5),
              #"reg_alpha": trial.suggest_float("reg_alpha",1e-4,10,log=True),
              "reg_lambda": trial.suggest_float("reg_lambda",1e-4,10,log=True),
    }
    
    gkf = GroupKFold(n_splits=5)
    mae_scores = []

    for train_idx, val_idx in gkf.split(X, y, groups=groups):

        X_train, X_val = X.iloc[train_idx], X.iloc[val_idx]
        y_train, y_val = y.iloc[train_idx], y.iloc[val_idx]
        
        model = xgb.XGBRegressor(**params)
        
        model.fit(
            X_train, y_train,
            eval_set=[(X_val, y_val)],
            verbose=False
        )
        
        preds = model.predict(X_val)
        mae_scores.append(mean_absolute_error(y_val, preds))

    return np.mean(mae_scores)

In [13]:
study = optuna.create_study(
    direction="minimize"
)

study.optimize(
    objective,
    n_trials=200,
    show_progress_bar=True
)

[I 2026-05-13 04:15:13,588] A new study created in memory with name: no-name-36b92a8f-c6d3-4af8-ac1f-b5726f259cd9

  0%|          | 0/200 [00:00<?, ?it/s]

[I 2026-05-13 04:15:14,861] Trial 0 finished with value: 0.8720156788825989 and parameters: {'n_estimators': 427, 'max_depth': 4, 'learning_rate': 0.0139878616549779, 'subsample': 0.7083427323302387, 'colsample_bytree': 0.6112550037382691, 'min_child_weight': 13, 'gamma': 4.498109147360447, 'reg_lambda': 0.23280777087136076}. Best is trial 0 with value: 0.8720156788825989.
[I 2026-05-13 04:15:16,814] Trial 1 finished with value: 0.8872463583946228 and parameters: {'n_estimators': 923, 'max_depth': 4, 'learning_rate': 0.06134800112506874, 'subsample': 0.6521454543656449, 'colsample_bytree': 0.7460009618910378, 'min_child_weight': 15, 'gamma': 3.377584394382918, 'reg_lambda': 0.00017264398782990313}. Best is trial 0 with value: 0.8720156788825989.
[I 2026-05-13 04:15:18,326] Trial 2 finished with value: 0.8587258577346801 and parameters: {'n_estimators': 511, 'max_depth': 4, 'learning_rate': 0.00764884808861747, 'subsample': 0.9535210694824068, 'colsample_bytree': 0.9587410817916595, 'min_child_weight': 9, 'gamma': 4.599508889303467, 'reg_lambda': 0.2412953330972376}. Best is trial 2 with value: 0.8587258577346801.
[I 2026-05-13 04:15:19,367] Trial 3 finished with value: 0.8670487761497497 and parameters: {'n_estimators': 377, 'max_depth': 9, 'learning_rate': 0.03421686203292058, 'subsample': 0.6410410206017243, 'colsample_bytree': 0.7447686481333307, 'min_child_weight': 10, 'gamma': 4.837322520071198, 'reg_lambda': 2.258485624631528}. Best is trial 2 with value: 0.8587258577346801.
[I 2026-05-13 04:15:21,509] Trial 4 finished with value: 0.9781233429908752 and parameters: {'n_estimators': 717, 'max_depth': 7, 'learning_rate': 0.07150430284941792, 'subsample': 0.5918980215563272, 'colsample_bytree': 0.5556908773215847, 'min_child_weight': 7, 'gamma': 0.1627999372328892, 'reg_lambda': 0.002363475981213016}. Best is trial 2 with value: 0.8587258577346801.
[I 2026-05-13 04:15:23,050] Trial 5 finished with value: 0.9346550345420838 and parameters: {'n_estimators': 797, 'max_depth': 6, 'learning_rate': 0.09528578072984996, 'subsample': 0.8669232167785511, 'colsample_bytree': 0.7375871833900607, 'min_child_weight': 2, 'gamma': 2.2786818866065115, 'reg_lambda': 0.031959371388908246}. Best is trial 2 with value: 0.8587258577346801.
[I 2026-05-13 04:15:25,228] Trial 6 finished with value: 0.9063663125038147 and parameters: {'n_estimators': 648, 'max_depth': 6, 'learning_rate': 0.0220251255772054, 'subsample': 0.9145661633507964, 'colsample_bytree': 0.5912838243716018, 'min_child_weight': 7, 'gamma': 0.6508598517083375, 'reg_lambda': 0.00959297565364592}. Best is trial 2 with value: 0.8587258577346801.
[I 2026-05-13 04:15:27,714] Trial 7 finished with value: 0.8845408320426941 and parameters: {'n_estimators': 773, 'max_depth': 10, 'learning_rate': 0.01318211362986428, 'subsample': 0.7063625570535568, 'colsample_bytree': 0.5942040475972925, 'min_child_weight': 13, 'gamma': 2.520116511613146, 'reg_lambda': 0.03109204842380984}. Best is trial 2 with value: 0.8587258577346801.
[I 2026-05-13 04:15:28,800] Trial 8 finished with value: 0.8683884382247925 and parameters: {'n_estimators': 456, 'max_depth': 3, 'learning_rate': 0.015074285180081831, 'subsample': 0.6987083375735247, 'colsample_bytree': 0.6145708201359779, 'min_child_weight': 10, 'gamma': 0.3648170691409286, 'reg_lambda': 0.19029678696449928}. Best is trial 2 with value: 0.8587258577346801.
[I 2026-05-13 04:15:30,435] Trial 9 finished with value: 0.9326352953910828 and parameters: {'n_estimators': 911, 'max_depth': 4, 'learning_rate': 0.06908794833440669, 'subsample': 0.8277124892888073, 'colsample_bytree': 0.595473426179316, 'min_child_weight': 4, 'gamma': 1.3561886601614592, 'reg_lambda': 4.718262747325958}. Best is trial 2 with value: 0.8587258577346801.
[I 2026-05-13 04:15:31,503] Trial 10 finished with value: 0.9898129224777221 and parameters: {'n_estimators': 280, 'max_depth': 8, 'learning_rate': 0.006789815729173913, 'subsample': 0.999877688454437, 'colsample_bytree': 0.9728380344690757, 'min_child_weight': 5, 'gamma': 3.8193828339100135, 'reg_lambda': 0.6350983170591745}. Best is trial 2 with value: 0.8587258577346801.
[I 2026-05-13 04:15:32,777] Trial 11 finished with value: 0.8750681281089783 and parameters: {'n_estimators': 490, 'max_depth': 10, 'learning_rate': 0.03560966813593473, 'subsample': 0.5005913976168058, 'colsample_bytree': 0.9700379379605991, 'min_child_weight': 10, 'gamma': 4.9382600150880736, 'reg_lambda': 9.695719756828822}. Best is trial 2 with value: 0.8587258577346801.
[I 2026-05-13 04:15:33,962] Trial 12 finished with value: 1.0988977909088136 and parameters: {'n_estimators': 293, 'max_depth': 8, 'learning_rate': 0.005080190591368825, 'subsample': 0.7831636459875395, 'colsample_bytree': 0.8846696099284965, 'min_child_weight': 10, 'gamma': 3.9479517296546294, 'reg_lambda': 1.3245359953829188}. Best is trial 2 with value: 0.8587258577346801.
[I 2026-05-13 04:15:35,315] Trial 13 finished with value: 0.8740310192108154 and parameters: {'n_estimators': 555, 'max_depth': 9, 'learning_rate': 0.0354491623896292, 'subsample': 0.5846045402129306, 'colsample_bytree': 0.8439952588709377, 'min_child_weight': 8, 'gamma': 4.980523140687418, 'reg_lambda': 1.5735328839174019}. Best is trial 2 with value: 0.8587258577346801.
[I 2026-05-13 04:15:35,998] Trial 14 finished with value: 0.870974087715149 and parameters: {'n_estimators': 217, 'max_depth': 5, 'learning_rate': 0.035490266562193645, 'subsample': 0.9922508624283435, 'colsample_bytree': 0.8232339853872037, 'min_child_weight': 11, 'gamma': 3.0229361142898314, 'reg_lambda': 0.08285149016890575}. Best is trial 2 with value: 0.8587258577346801.
[I 2026-05-13 04:15:37,632] Trial 15 finished with value: 0.8706787824630737 and parameters: {'n_estimators': 385, 'max_depth': 7, 'learning_rate': 0.00931735781592438, 'subsample': 0.8986681378518255, 'colsample_bytree': 0.7857004969964116, 'min_child_weight': 12, 'gamma': 4.317369396441843, 'reg_lambda': 0.57763267783382}. Best is trial 2 with value: 0.8587258577346801.
[I 2026-05-13 04:15:39,032] Trial 16 finished with value: 0.8779883027076721 and parameters: {'n_estimators': 576, 'max_depth': 3, 'learning_rate': 0.026047133681184352, 'subsample': 0.7793618358879051, 'colsample_bytree': 0.6945801799893754, 'min_child_weight': 5, 'gamma': 3.47542110889077, 'reg_lambda': 2.5009024979704564}. Best is trial 2 with value: 0.8587258577346801.
[I 2026-05-13 04:15:40,503] Trial 17 finished with value: 0.8701678514480591 and parameters: {'n_estimators': 346, 'max_depth': 9, 'learning_rate': 0.021185855876755078, 'subsample': 0.6381671591031916, 'colsample_bytree': 0.9197203210727056, 'min_child_weight': 15, 'gamma': 1.7729341646373185, 'reg_lambda': 0.003778466173943155}. Best is trial 2 with value: 0.8587258577346801.
[I 2026-05-13 04:15:42,276] Trial 18 finished with value: 0.8704108357429504 and parameters: {'n_estimators': 526, 'max_depth': 5, 'learning_rate': 0.009519623549046716, 'subsample': 0.5091178211090445, 'colsample_bytree': 0.6712728070787277, 'min_child_weight': 8, 'gamma': 4.390066112158782, 'reg_lambda': 0.2580489013061269}. Best is trial 2 with value: 0.8587258577346801.
[I 2026-05-13 04:15:43,908] Trial 19 finished with value: 0.8858211874961853 and parameters: {'n_estimators': 641, 'max_depth': 8, 'learning_rate': 0.04804399779079632, 'subsample': 0.9436746749604007, 'colsample_bytree': 0.5031443657144441, 'min_child_weight': 9, 'gamma': 2.9205716972970515, 'reg_lambda': 8.724570897858904}. Best is trial 2 with value: 0.8587258577346801.
[I 2026-05-13 04:15:45,569] Trial 20 finished with value: 0.9496555685997009 and parameters: {'n_estimators': 385, 'max_depth': 5, 'learning_rate': 0.005318623195422056, 'subsample': 0.8313227323342088, 'colsample_bytree': 0.9121601108880927, 'min_child_weight': 1, 'gamma': 3.9739130006413603, 'reg_lambda': 0.059188620094163605}. Best is trial 2 with value: 0.8587258577346801.
[I 2026-05-13 04:15:46,861] Trial 21 finished with value: 0.8674632430076599 and parameters: {'n_estimators': 457, 'max_depth': 3, 'learning_rate': 0.014977077659858548, 'subsample': 0.71713428682564, 'colsample_bytree': 0.6713469247873816, 'min_child_weight': 11, 'gamma': 1.2570852084469593, 'reg_lambda': 0.18593559204987092}. Best is trial 2 with value: 0.8587258577346801.
[I 2026-05-13 04:15:48,227] Trial 22 finished with value: 0.8616748452186584 and parameters: {'n_estimators': 475, 'max_depth': 3, 'learning_rate': 0.009436461340238556, 'subsample': 0.7409756350515044, 'colsample_bytree': 0.6830238076363055, 'min_child_weight': 12, 'gamma': 1.2179676325130289, 'reg_lambda': 0.6350926134991214}. Best is trial 2 with value: 0.8587258577346801.
[I 2026-05-13 04:15:49,713] Trial 23 finished with value: 0.9047963380813598 and parameters: {'n_estimators': 308, 'max_depth': 4, 'learning_rate': 0.008128379425536151, 'subsample': 0.6559257420853023, 'colsample_bytree': 0.7062479718626223, 'min_child_weight': 13, 'gamma': 1.024193906216176, 'reg_lambda': 0.5851315410322969}. Best is trial 2 with value: 0.8587258577346801.
[I 2026-05-13 04:15:51,631] Trial 24 finished with value: 0.860201072692871 and parameters: {'n_estimators': 617, 'max_depth': 3, 'learning_rate': 0.010998996872880534, 'subsample': 0.7649949927294557, 'colsample_bytree': 0.7961399217771029, 'min_child_weight': 12, 'gamma': 2.1615579384449455, 'reg_lambda': 2.529824294366649}. Best is trial 2 with value: 0.8587258577346801.
[I 2026-05-13 04:15:53,346] Trial 25 finished with value: 0.8627862930297852 and parameters: {'n_estimators': 624, 'max_depth': 3, 'learning_rate': 0.011193629704744603, 'subsample': 0.7529465178033506, 'colsample_bytree': 0.8045712536471413, 'min_child_weight': 14, 'gamma': 2.079665743233111, 'reg_lambda': 0.8203733036615767}. Best is trial 2 with value: 0.8587258577346801.
[I 2026-05-13 04:15:55,181] Trial 26 finished with value: 0.8538816213607788 and parameters: {'n_estimators': 715, 'max_depth': 3, 'learning_rate': 0.006815187196396083, 'subsample': 0.8236587935537665, 'colsample_bytree': 0.8674939106582525, 'min_child_weight': 11, 'gamma': 1.7533444967917673, 'reg_lambda': 3.7705538405243613}. Best is trial 26 with value: 0.8538816213607788.
[I 2026-05-13 04:15:57,274] Trial 27 finished with value: 0.8527270674705505 and parameters: {'n_estimators': 696, 'max_depth': 4, 'learning_rate': 0.006838354515128459, 'subsample': 0.8123359102035262, 'colsample_bytree': 0.8659760933720978, 'min_child_weight': 12, 'gamma': 1.9916688237496447, 'reg_lambda': 3.9354066360904656}. Best is trial 27 with value: 0.8527270674705505.
[I 2026-05-13 04:16:00,207] Trial 28 finished with value: 0.8535655975341797 and parameters: {'n_estimators': 853, 'max_depth': 5, 'learning_rate': 0.006617519943607916, 'subsample': 0.8244355266373685, 'colsample_bytree': 0.8695547127414559, 'min_child_weight': 9, 'gamma': 1.6264097310691206, 'reg_lambda': 4.701961974236977}. Best is trial 27 with value: 0.8527270674705505.
[I 2026-05-13 04:16:03,201] Trial 29 finished with value: 0.8537689685821533 and parameters: {'n_estimators': 860, 'max_depth': 5, 'learning_rate': 0.006479890663112298, 'subsample': 0.8202250983318009, 'colsample_bytree': 0.863345110487586, 'min_child_weight': 13, 'gamma': 1.6757052969893085, 'reg_lambda': 4.503925393621487}. Best is trial 27 with value: 0.8527270674705505.
[I 2026-05-13 04:16:06,034] Trial 30 finished with value: 0.8547327995300293 and parameters: {'n_estimators': 854, 'max_depth': 5, 'learning_rate': 0.006236863271862769, 'subsample': 0.8659804619826773, 'colsample_bytree': 0.9201539303444501, 'min_child_weight': 13, 'gamma': 1.6628947698886487, 'reg_lambda': 5.452462185145197}. Best is trial 27 with value: 0.8527270674705505.
[I 2026-05-13 04:16:08,836] Trial 31 finished with value: 0.8556548714637756 and parameters: {'n_estimators': 977, 'max_depth': 4, 'learning_rate': 0.006214441317030835, 'subsample': 0.8195601911539926, 'colsample_bytree': 0.8674747197830377, 'min_child_weight': 14, 'gamma': 1.778246881308618, 'reg_lambda': 4.457171966379693}. Best is trial 27 with value: 0.8527270674705505.
[I 2026-05-13 04:16:11,490] Trial 32 finished with value: 0.8665102124214172 and parameters: {'n_estimators': 702, 'max_depth': 6, 'learning_rate': 0.0073399067791996495, 'subsample': 0.8031349469914386, 'colsample_bytree': 0.870341322763631, 'min_child_weight': 11, 'gamma': 0.8348326397876715, 'reg_lambda': 0.0003923347715686107}. Best is trial 27 with value: 0.8527270674705505.
[I 2026-05-13 04:16:14,660] Trial 33 finished with value: 0.855693781375885 and parameters: {'n_estimators': 831, 'max_depth': 5, 'learning_rate': 0.0057106792455772866, 'subsample': 0.8591895806132658, 'colsample_bytree': 0.8380547536523892, 'min_child_weight': 14, 'gamma': 2.70797642309292, 'reg_lambda': 4.593150443411227}. Best is trial 27 with value: 0.8527270674705505.
[I 2026-05-13 04:16:17,093] Trial 34 finished with value: 0.8602229833602906 and parameters: {'n_estimators': 717, 'max_depth': 4, 'learning_rate': 0.007674290788253786, 'subsample': 0.8977097743229151, 'colsample_bytree': 0.9368305743405473, 'min_child_weight': 9, 'gamma': 1.629737049524213, 'reg_lambda': 1.5681767878527972}. Best is trial 27 with value: 0.8527270674705505.
[I 2026-05-13 04:16:19,547] Trial 35 finished with value: 0.8632772445678711 and parameters: {'n_estimators': 903, 'max_depth': 4, 'learning_rate': 0.012399980423036472, 'subsample': 0.852414507805497, 'colsample_bytree': 0.9954312838611702, 'min_child_weight': 12, 'gamma': 2.016685447150234, 'reg_lambda': 8.922143755127317}. Best is trial 27 with value: 0.8527270674705505.
[I 2026-05-13 04:16:21,547] Trial 36 finished with value: 0.8679444909095764 and parameters: {'n_estimators': 779, 'max_depth': 6, 'learning_rate': 0.0175909910303125, 'subsample': 0.8057244779359117, 'colsample_bytree': 0.7683103330639763, 'min_child_weight': 11, 'gamma': 2.4581068666796266, 'reg_lambda': 3.3158443036941825}. Best is trial 27 with value: 0.8527270674705505.
[I 2026-05-13 04:16:23,780] Trial 37 finished with value: 0.8710160970687866 and parameters: {'n_estimators': 996, 'max_depth': 5, 'learning_rate': 0.008652446158461115, 'subsample': 0.9286328144296598, 'colsample_bytree': 0.8918998538070073, 'min_child_weight': 7, 'gamma': 1.4329229857189638, 'reg_lambda': 1.0938679209224966}. Best is trial 27 with value: 0.8527270674705505.
[I 2026-05-13 04:16:25,733] Trial 38 finished with value: 0.8595785975456238 and parameters: {'n_estimators': 688, 'max_depth': 4, 'learning_rate': 0.006381725195611456, 'subsample': 0.877616887136827, 'colsample_bytree': 0.8506168585830963, 'min_child_weight': 9, 'gamma': 0.5759495108242954, 'reg_lambda': 0.00013680543081564636}. Best is trial 27 with value: 0.8527270674705505.
[I 2026-05-13 04:16:29,241] Trial 39 finished with value: 0.869751250743866 and parameters: {'n_estimators': 853, 'max_depth': 6, 'learning_rate': 0.0074176149890599835, 'subsample': 0.7321922946487145, 'colsample_bytree': 0.8167007060677542, 'min_child_weight': 15, 'gamma': 0.0007185160460148055, 'reg_lambda': 0.36770372196485396}. Best is trial 27 with value: 0.8527270674705505.
[I 2026-05-13 04:16:31,557] Trial 40 finished with value: 0.868412435054779 and parameters: {'n_estimators': 749, 'max_depth': 5, 'learning_rate': 0.01077387648977335, 'subsample': 0.7909608039614602, 'colsample_bytree': 0.9428667800059548, 'min_child_weight': 13, 'gamma': 2.01397666255325, 'reg_lambda': 0.00034058656547956235}. Best is trial 27 with value: 0.8527270674705505.
[I 2026-05-13 04:16:34,677] Trial 41 finished with value: 0.8531487822532654 and parameters: {'n_estimators': 836, 'max_depth': 5, 'learning_rate': 0.005923193118216848, 'subsample': 0.8440239007017273, 'colsample_bytree': 0.9031451795881941, 'min_child_weight': 13, 'gamma': 1.5835032560329774, 'reg_lambda': 6.820389528896289}. Best is trial 27 with value: 0.8527270674705505.
[I 2026-05-13 04:16:37,100] Trial 42 finished with value: 0.8529950141906738 and parameters: {'n_estimators': 816, 'max_depth': 4, 'learning_rate': 0.005564822861708676, 'subsample': 0.8377779195432495, 'colsample_bytree': 0.8982588138568921, 'min_child_weight': 14, 'gamma': 2.372583397351266, 'reg_lambda': 2.49390959369027}. Best is trial 27 with value: 0.8527270674705505.
[I 2026-05-13 04:16:39,759] Trial 43 finished with value: 0.8593681216239929 and parameters: {'n_estimators': 823, 'max_depth': 5, 'learning_rate': 0.005569222015498069, 'subsample': 0.8507482859290736, 'colsample_bytree': 0.9117986681817266, 'min_child_weight': 14, 'gamma': 2.3740653452775655, 'reg_lambda': 1.9917465855334264}. Best is trial 27 with value: 0.8527270674705505.
[I 2026-05-13 04:16:42,658] Trial 44 finished with value: 0.8529667615890503 and parameters: {'n_estimators': 947, 'max_depth': 7, 'learning_rate': 0.005090848239437466, 'subsample': 0.8931512819073341, 'colsample_bytree': 0.9011047576605417, 'min_child_weight': 13, 'gamma': 2.6627830063443785, 'reg_lambda': 6.69855827868016}. Best is trial 27 with value: 0.8527270674705505.
[I 2026-05-13 04:16:45,467] Trial 45 finished with value: 0.8522946119308472 and parameters: {'n_estimators': 947, 'max_depth': 7, 'learning_rate': 0.005694702572329295, 'subsample': 0.8936478610927154, 'colsample_bytree': 0.8935453277325752, 'min_child_weight': 15, 'gamma': 2.664393545082434, 'reg_lambda': 9.267535407814542}. Best is trial 45 with value: 0.8522946119308472.
[I 2026-05-13 04:16:48,588] Trial 46 finished with value: 0.8538359999656677 and parameters: {'n_estimators': 953, 'max_depth': 7, 'learning_rate': 0.0050301474731148646, 'subsample': 0.9666920141512572, 'colsample_bytree': 0.8951775372418942, 'min_child_weight': 15, 'gamma': 2.7905998980449653, 'reg_lambda': 7.8863794019124915}. Best is trial 45 with value: 0.8522946119308472.
[I 2026-05-13 04:16:51,224] Trial 47 finished with value: 0.8565921068191529 and parameters: {'n_estimators': 944, 'max_depth': 7, 'learning_rate': 0.0057628994347357024, 'subsample': 0.8962917950127863, 'colsample_bytree': 0.9696933703843112, 'min_child_weight': 14, 'gamma': 3.295864242120314, 'reg_lambda': 2.5088840821951957}. Best is trial 45 with value: 0.8522946119308472.
[I 2026-05-13 04:16:54,098] Trial 48 finished with value: 0.8590950846672059 and parameters: {'n_estimators': 885, 'max_depth': 8, 'learning_rate': 0.005014080101436964, 'subsample': 0.9207567354803046, 'colsample_bytree': 0.9471252592834958, 'min_child_weight': 15, 'gamma': 3.1595696175545256, 'reg_lambda': 0.013973692455462145}. Best is trial 45 with value: 0.8522946119308472.
[I 2026-05-13 04:16:56,411] Trial 49 finished with value: 0.8594983339309692 and parameters: {'n_estimators': 801, 'max_depth': 7, 'learning_rate': 0.008288395078864304, 'subsample': 0.8821577298278472, 'colsample_bytree': 0.8929683266267916, 'min_child_weight': 14, 'gamma': 2.7033643217337744, 'reg_lambda': 1.099248996810549}. Best is trial 45 with value: 0.8522946119308472.
[I 2026-05-13 04:16:59,863] Trial 50 finished with value: 0.8635727643966675 and parameters: {'n_estimators': 940, 'max_depth': 6, 'learning_rate': 0.00567834707922336, 'subsample': 0.961052852353262, 'colsample_bytree': 0.9909288564767884, 'min_child_weight': 12, 'gamma': 3.5382389364516875, 'reg_lambda': 7.183268361711178}. Best is trial 45 with value: 0.8522946119308472.
[I 2026-05-13 04:17:03,241] Trial 51 finished with value: 0.8535972833633423 and parameters: {'n_estimators': 892, 'max_depth': 6, 'learning_rate': 0.007017292545458674, 'subsample': 0.8407850588948296, 'colsample_bytree': 0.8330487814514589, 'min_child_weight': 13, 'gamma': 2.3689668882430697, 'reg_lambda': 6.304751460927049}. Best is trial 45 with value: 0.8522946119308472.

In [14]:
trial_df = study.trials_dataframe()
fig = px.line(
    trial_df,
    x="number",
    y="value",
    title="Optuna Optimization History",template = "presentation"
)
fig.show()

In [15]:
print("Best MAE:")
print(study.best_value)

print("\nBest Parameters:")
print(study.best_params)

Best MAE:
0.8476357460021973

Best Parameters:
{'n_estimators': 800, 'max_depth': 8, 'learning_rate': 0.016938531134270917, 'subsample': 0.9809586622448973, 'colsample_bytree': 0.8102631339150652, 'min_child_weight': 14, 'gamma': 3.7355806317338365, 'reg_lambda': 9.843327067497283}

In [16]:
def evaluate(df, feature_list, best_params, target_col='G3'):
    X = df[feature_list]
    y = df[target_col]
    groups = df['student_id']
    
    gkf = GroupKFold(n_splits=5)
    
    mae_scores = []
    mse_scores = []
    r2_scores = []
    
    print(f"\n--- Training Model with {len(feature_list)} features ---")
    
    for train_idx, val_idx in gkf.split(X, y, groups=groups):
        X_train, X_val = X.iloc[train_idx], X.iloc[val_idx]
        y_train, y_val = y.iloc[train_idx], y.iloc[val_idx]
        
        model = xgb.XGBRegressor(**best_params, tree_method= "hist",objective= "reg:squarederror",random_state= 42,
              enable_categorical =True)
        
        model.fit(
            X_train, y_train,
            eval_set=[(X_val, y_val)],
            verbose=False
        )
        
        preds = model.predict(X_val)
        mae_scores.append(mean_absolute_error(y_val, preds))
        mse_scores.append(mean_squared_error(y_val, preds))
        r2_scores.append(r2_score(y_val, preds))
        
    print('MAE :',mae_scores)    
    print(f"Average MAE: {np.mean(mae_scores):.4f}")
    print('MSE :',mse_scores)    
    print(f"Average MSE: {np.mean(mse_scores):.4f}")
    print('r2_scores : ',r2_scores)
    print(f"Average R2: {np.mean(r2_scores):.4f}")

In [17]:
# evaluating Model 3 (post G2 exam)
evaluate(df, features_model3, best_params=study.best_params)

--- Training Model with 33 features ---
MAE : [0.7974538207054138, 0.8176916241645813, 0.8504562973976135, 0.8679565787315369, 0.9046204090118408]
Average MAE: 0.8476
MSE : [1.5725754499435425, 1.751560091972351, 1.5326460599899292, 2.4797310829162598, 2.316154956817627]
Average MSE: 1.9305
r2_scores :  [0.8852112293243408, 0.8597636222839355, 0.8977338671684265, 0.845866322517395, 0.8648068308830261]
Average R2: 0.8707

In [18]:
# final model 3 (using the whole data)
model_3 = xgb.XGBRegressor(**study.best_params, tree_method= "hist",objective= "reg:squarederror",random_state= 42,
              enable_categorical =True)
model_3.fit(
            X, y,
            verbose=True
        )
pred = model_3.predict(X)
mean_absolute_error(pred,y)

0.6771877408027649

In [19]:
model_3.save_model("model_3.json")

### Feature Importance

In [21]:
importance = model_3.feature_importances_

feature_imp_df = (
    pd.DataFrame({
        "feature": X.columns,
        "importance": importance
    })
    .sort_values(
        "importance",
        ascending=False
    )
)

feature_imp_df

       feature  importance
32          G2    0.342962
31          G1    0.284532
29    absences    0.051801
30     subject    0.020928
2          age    0.019184
14    failures    0.019112
0       school    0.016400
18  activities    0.014425
10      reason    0.012360
23      famrel    0.011956
1          sex    0.011481
7         Fedu    0.011410
20      higher    0.011380
25       goout    0.011202
22    romantic    0.010637
19     nursery    0.010393
13   studytime    0.010277
8         Mjob    0.010225
9         Fjob    0.010073
28      health    0.010030
24    freetime    0.009410
27        Walc    0.009252
15   schoolsup    0.009063
16      famsup    0.009039
11    guardian    0.009034
3      address    0.009026
12  traveltime    0.008981
4      famsize    0.008403
26        Dalc    0.007222
6         Medu    0.007085
17        paid    0.006363
21    internet    0.006353
5      Pstatus    0.000000

In [22]:
X

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,subject,G1,G2
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,Maths,5,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,Maths,5,5
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,Maths,7,8
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,Maths,15,14
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,Maths,6,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1039,MS,F,19,R,GT3,T,2,3,services,other,...,5,4,2,1,2,5,4,Portuguese,10,11
1040,MS,F,18,U,LE3,T,3,1,teacher,services,...,4,3,4,1,1,1,4,Portuguese,15,15
1041,MS,F,18,U,GT3,T,1,1,other,other,...,1,1,1,1,1,5,6,Portuguese,11,12
1042,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,6,Portuguese,10,10
1043,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,4,Portuguese,10,11

In [23]:
X.columns

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'subject', 'G1', 'G2'],
      dtype='str')

In [31]:
X.select_dtypes(include='category')

,school,sex,address,famsize,Pstatus,Mjob,Fjob,reason,guardian,schoolsup,famsup,paid,activities,nursery,higher,internet,romantic,subject
0,GP,F,U,GT3,A,at_home,teacher,course,mother,yes,no,no,no,yes,yes,no,no,Maths
1,GP,F,U,GT3,T,at_home,other,course,father,no,yes,no,no,no,yes,yes,no,Maths
2,GP,F,U,LE3,T,at_home,other,other,mother,yes,no,yes,no,yes,yes,yes,no,Maths
3,GP,F,U,GT3,T,health,services,home,mother,no,yes,yes,yes,yes,yes,yes,yes,Maths
4,GP,F,U,GT3,T,other,other,home,father,no,yes,yes,no,yes,yes,no,no,Maths
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1039,MS,F,R,GT3,T,services,other,course,mother,no,no,no,yes,no,yes,yes,no,Portuguese
1040,MS,F,U,LE3,T,teacher,services,course,mother,no,yes,no,no,yes,yes,yes,no,Portuguese
1041,MS,F,U,GT3,T,other,other,course,mother,no,no,no,yes,yes,yes,no,no,Portuguese
1042,MS,M,U,LE3,T,services,services,course,mother,no,no,no,no,no,yes,yes,no,Portuguese
1043,MS,M,R,LE3,T,services,other,course,mother,no,no,no,no,no,yes,yes,no,Portuguese

In [43]:
exact_categories_data = {}
temp_df = X.select_dtypes(include='category')
for i in temp_df.columns :
    exact_categories_data[i] = list(temp_df[i].unique())

In [44]:
exact_categories_data

{'school': ['GP', 'MS'],
 'sex': ['F', 'M'],
 'address': ['U', 'R'],
 'famsize': ['GT3', 'LE3'],
 'Pstatus': ['A', 'T'],
 'Mjob': ['at_home', 'health', 'other', 'services', 'teacher'],
 'Fjob': ['teacher', 'other', 'services', 'health', 'at_home'],
 'reason': ['course', 'other', 'home', 'reputation'],
 'guardian': ['mother', 'father', 'other'],
 'schoolsup': ['yes', 'no'],
 'famsup': ['no', 'yes'],
 'paid': ['no', 'yes'],
 'activities': ['no', 'yes'],
 'nursery': ['yes', 'no'],
 'higher': ['yes', 'no'],
 'internet': ['no', 'yes'],
 'romantic': ['no', 'yes'],
 'subject': ['Maths', 'Portuguese']}

In [45]:
print(exact_categories_data)

{'school': ['GP', 'MS'], 'sex': ['F', 'M'], 'address': ['U', 'R'], 'famsize': ['GT3', 'LE3'], 'Pstatus': ['A', 'T'], 'Mjob': ['at_home', 'health', 'other', 'services', 'teacher'], 'Fjob': ['teacher', 'other', 'services', 'health', 'at_home'], 'reason': ['course', 'other', 'home', 'reputation'], 'guardian': ['mother', 'father', 'other'], 'schoolsup': ['yes', 'no'], 'famsup': ['no', 'yes'], 'paid': ['no', 'yes'], 'activities': ['no', 'yes'], 'nursery': ['yes', 'no'], 'higher': ['yes', 'no'], 'internet': ['no', 'yes'], 'romantic': ['no', 'yes'], 'subject': ['Maths', 'Portuguese']}